const { HTMLField, SchemaField, NumberField, StringField, FilePathField, ArrayField, BooleanField, ObjectField } =
  foundry.data.fields;

export class NpcData extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    const requiredInteger = { required: true, nullable: false, integer: true };
    return {
      hp: new SchemaField({
        value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
        min: new NumberField({ ...requiredInteger, min: 0, initial: 0 }),
        max: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
        adj: new NumberField({ ...requiredInteger, min: 0, initial: 0 }),
      }),
      stats: new SchemaField({
        siz: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 0 }),
          create: new NumberField({ ...requiredInteger, initial: 0 }),
          poison: new NumberField({ ...requiredInteger, initial: 0 }),
          disease: new NumberField({ ...requiredInteger, initial: 0 }),
          sol: new NumberField({ ...requiredInteger, initial: 0 }),
          age: new NumberField({ ...requiredInteger, initial: 0 }),
          major: new NumberField({ ...requiredInteger, initial: 0 }),
          winter: new NumberField({ ...requiredInteger, initial: 0 }),
          growth: new NumberField({ ...requiredInteger, initial: 0 }),
          formula: new StringField({ required: true, initial: "" }),
        }),
        dex: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 0 }),
          create: new NumberField({ ...requiredInteger, initial: 0 }),
          poison: new NumberField({ ...requiredInteger, initial: 0 }),
          disease: new NumberField({ ...requiredInteger, initial: 0 }),
          sol: new NumberField({ ...requiredInteger, initial: 0 }),
          age: new NumberField({ ...requiredInteger, initial: 0 }),
          major: new NumberField({ ...requiredInteger, initial: 0 }),
          winter: new NumberField({ ...requiredInteger, initial: 0 }),
          growth: new NumberField({ ...requiredInteger, initial: 0 }),
          formula: new StringField({ required: true, initial: "" }),
        }),
        str: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 0 }),
          create: new NumberField({ ...requiredInteger, initial: 0 }),
          poison: new NumberField({ ...requiredInteger, initial: 0 }),
          disease: new NumberField({ ...requiredInteger, initial: 0 }),
          sol: new NumberField({ ...requiredInteger, initial: 0 }),
          age: new NumberField({ ...requiredInteger, initial: 0 }),
          major: new NumberField({ ...requiredInteger, initial: 0 }),
          winter: new NumberField({ ...requiredInteger, initial: 0 }),
          growth: new NumberField({ ...requiredInteger, initial: 0 }),
          formula: new StringField({ required: true, initial: "" }),
        }),
        con: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 0 }),
          create: new NumberField({ ...requiredInteger, initial: 0 }),
          poison: new NumberField({ ...requiredInteger, initial: 0 }),
          disease: new NumberField({ ...requiredInteger, initial: 0 }),
          sol: new NumberField({ ...requiredInteger, initial: 0 }),
          age: new NumberField({ ...requiredInteger, initial: 0 }),
          major: new NumberField({ ...requiredInteger, initial: 0 }),
          winter: new NumberField({ ...requiredInteger, initial: 0 }),
          growth: new NumberField({ ...requiredInteger, initial: 0 }),
          formula: new StringField({ required: true, initial: "" }),
        }),
        app: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 0 }),
          create: new NumberField({ ...requiredInteger, initial: 0 }),
          poison: new NumberField({ ...requiredInteger, initial: 0 }),
          disease: new NumberField({ ...requiredInteger, initial: 0 }),
          sol: new NumberField({ ...requiredInteger, initial: 0 }),
          age: new NumberField({ ...requiredInteger, initial: 0 }),
          major: new NumberField({ ...requiredInteger, initial: 0 }),
          winter: new NumberField({ ...requiredInteger, initial: 0 }),
          growth: new NumberField({ ...requiredInteger, initial: 0 }),
          formula: new StringField({ required: true, initial: "" }),
        }),
      }),
      coatOfArms: new FilePathField({
        required: true,
        categories: ["IMAGE"],
        initial: "systems/Pendragon/assets/Icons/checked-shield.svg",
      }),
      gloryAward: new NumberField({ ...requiredInteger, initial: 0 }),
      gloryTotal: new NumberField({ ...requiredInteger, initial: 0 }),
      woundTotal: new NumberField({ ...requiredInteger, initial: 0 }),
      altMove: new NumberField({ ...requiredInteger, initial: 0 }),
      manMove: new NumberField({ ...requiredInteger, initial: 0 }),
      valMod: new NumberField({ ...requiredInteger, initial: 0 }),
      manArm: new NumberField({ ...requiredInteger, initial: 0 }),
      manShd: new NumberField({ ...requiredInteger, initial: 0 }),
      equippedHands: new SchemaField({
        primary: new StringField({ required: true, initial: "" }),
        secondary: new StringField({ required: true, initial: "" }),
      }),
      manMaxHP: new NumberField({ ...requiredInteger, initial: 0 }),
      manKnockdown: new NumberField({ ...requiredInteger, initial: 0 }),
      manMjrWnd: new NumberField({ ...requiredInteger, initial: 0 }),
      manDmg: new NumberField({ ...requiredInteger, initial: 0 }),
      manHealRate: new NumberField({ ...requiredInteger, initial: 0 }),
      manUnconscious: new NumberField({ ...requiredInteger, initial: 0 }),
      lock: new BooleanField({ initial: false }),
      weaponExp: new BooleanField({ initial: true }),
      armorExp: new BooleanField({ initial: true }),
      skillExp: new BooleanField({ initial: true }),
      traitExp: new BooleanField({ initial: true }),
      passionExp: new BooleanField({ initial: true }),
      horseExp: new BooleanField({ initial: true }),
      talentExp: new BooleanField({ initial: true }),
      noteView: new BooleanField({ initial: false }),
      playerNotesView: new BooleanField({ initial: false }),
      baseStats: new BooleanField({ initial: false }),
      description: new HTMLField({ initial: "" }),
      playerNotes: new HTMLField({ initial: "" }),
      altMoveTitle: new StringField({ initial: "Alt Move" }),
      ransom: new StringField({ initial: "" }),
      kv: new StringField({ initial: "" }),
      random: new ArrayField(new ObjectField()),
    };
  }
}
